INSERT INTO CUSTOMER (LAST_NAME, FIRST_NAME, SOCIAL_SECURITY_NUMBER)
VALUES ('Kyrkos', 'Marios', 'SSN-1111111111');
INSERT INTO CUSTOMER (LAST_NAME, FIRST_NAME, SOCIAL_SECURITY_NUMBER)
VALUES ('Doe', 'John', 'SSN-1111111123');

INSERT INTO ACCOUNT (CUSTOMER_ID, BALANCE, ACCOUNT_TYPE)
VALUES (1, 2000, 'SAVINGS');
INSERT INTO ACCOUNT (CUSTOMER_ID, BALANCE, ACCOUNT_TYPE)
VALUES (1, 4000, 'SAVINGS');
INSERT INTO ACCOUNT (CUSTOMER_ID, BALANCE, ACCOUNT_TYPE)
VALUES (2, 10000, 'SAVINGS');

INSERT INTO TRANSACTION (ACCOUNT_ID, AMOUNT)
VALUES (1, 1000);
INSERT INTO TRANSACTION (ACCOUNT_ID, AMOUNT)
VALUES (1, -500);
INSERT INTO TRANSACTION (ACCOUNT_ID, AMOUNT)
VALUES (2, 5500);